version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/workflow_platform"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "12306hujunjie"
    labels:
      - "dependencies"
      - "python"