version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: workflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workflow_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: workflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: workflow-app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/workflow_platform
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-secret-key-here}
      DEBUG: ${DEBUG:-false}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    command: uvicorn api_gateway.main:app --host 0.0.0.0 --port 8000 --reload

  # Optional: Database migration service
  migrate:
    build: .
    container_name: workflow-migrate
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/workflow_platform
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    command: alembic upgrade head
    profiles:
      - migrate

volumes:
  postgres_data:
  redis_data: